name: .NET Core Desktop

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:    
    - name: Set env
      run: | 
        $regexResult = $env:GITHUB_REF -match 'refs\/heads\/master\/(.*)'
        echo "SHOULD_RELEASE=$regexResult" >> $env:GITHUB_ENV
        $matchGroup = $Matches.1
        echo "RELEASE_VERSION=$matchGroup" >> $env:GITHUB_ENV
      
    - name: Test
      run: |
        echo $env:RELEASE_VERSION
    
    - name: TestShouldNotRun
      if: ${{ env.SHOULD_RELEASE == true }}
      run: |
        echo $env:RELEASE_VERSION
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build application
      run: dotnet build
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Pack app
      run: dotnet publish --no-restore -o output --self-contained false
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: output
